from app.models import db, BusinessImage, environment, SCHEMA
import datetime
from sqlalchemy.sql import text

def seed_businesses_images():
    italian_one_previmage = BusinessImage(business_id=1, user_id=1, image_url="https://www.foodrepublic.com/img/gallery/100-italian-fooddrink-words-and-phrases/l-intro-1684783348.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_two_previmage = BusinessImage(business_id=2, user_id=2, image_url="https://images.pexels.com/photos/6287539/pexels-photo-6287539.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_three_previmage = BusinessImage(business_id=3, user_id=3, image_url="https://images.pexels.com/photos/1487511/pexels-photo-1487511.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_four_previmage = BusinessImage(business_id=4, user_id=4, image_url="https://images.pexels.com/photos/6287543/pexels-photo-6287543.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_five_previmage = BusinessImage(business_id=5, user_id=5, image_url="https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_six_previmage = BusinessImage(business_id=6, user_id=6, image_url="https://images.pexels.com/photos/8864543/pexels-photo-8864543.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_one_previmage = BusinessImage(business_id=7, user_id=1, image_url="https://media.timeout.com/images/100292153/750/562/image.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_two_previmage = BusinessImage(business_id=8, user_id=2, image_url="https://images.pexels.com/photos/3073970/pexels-photo-3073970.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_three_previmage = BusinessImage(business_id=9, user_id=3, image_url="https://media.istockphoto.com/id/469128438/photo/combination-mexican-fajitas-with-shrimp-chicken-and-beef.jpg?b=1&s=612x612&w=0&k=20&c=7vMNm0P5Ypdq4-f6jE1NMxGjiW0C2WQkUC8N6wU6SGs=", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_four_previmage = BusinessImage(business_id=10, user_id=4, image_url="https://images.pexels.com/photos/13592690/pexels-photo-13592690.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_five_previmage = BusinessImage(business_id=11, user_id=5, image_url="https://images.pexels.com/photos/6605198/pexels-photo-6605198.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_six_previmage = BusinessImage(business_id=12, user_id=6, image_url="https://media.istockphoto.com/id/485546286/photo/taco-dinner-closeup.jpg?b=1&s=612x612&w=0&k=20&c=6aLHKUN6AuNcYwkFX1ePJrlvVfSgdYbXVdOsi8eI9DQ=", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_seven_previmage = BusinessImage(business_id=13, user_id=7, image_url="https://images.pexels.com/photos/5929764/pexels-photo-5929764.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_one_previmage = BusinessImage(business_id=14, user_id=1, image_url="https://shef.com/homemade-food/wp-content/uploads/lebanese-mezze-middle-eastern-food-scaled-e1662414361114.jpeg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_two_previmage = BusinessImage(business_id=15, user_id=2, image_url="https://media.istockphoto.com/id/1271870386/photo/arabic-traditional-cuisine-middle-eastern-meze-with-pita-olives-colorful-hummus-falafel.jpg?b=1&s=612x612&w=0&k=20&c=p6TfdXa8y99yUgclNFzr4Y6NMTcUkzHXlCGik1lkU9c=", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_three_previmage = BusinessImage(business_id=16, user_id=3, image_url="https://media.istockphoto.com/id/1175505781/photo/arabic-and-middle-eastern-dinner-table-hummus-tabbouleh-salad-fattoush-salad-pita-meat-kebab.jpg?b=1&s=612x612&w=0&k=20&c=GOrMA3MILTELKLsXVuuRwoWayj28AnjKKcYL8uFMm-A=", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_four_previmage = BusinessImage(business_id=17, user_id=4, image_url="https://images.pexels.com/photos/4046770/pexels-photo-4046770.jpeg?auto=compress&cs=tinysrgb&w=600", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_five_previmage = BusinessImage(business_id=18, user_id=5, image_url="https://assets.westchestermagazine.com/2021/11/middle-eastern-food.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_six_previmage = BusinessImage(business_id=19, user_id=6, image_url="https://www.emeraldpalate.com/wp-content/uploads/2022/07/Mediterranean-Food-in-Seattle-FEATURE-IMAGE.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_one_previmage = BusinessImage(business_id=20, user_id=1, image_url="https://www.swedishnomad.com/wp-content/images/2018/09/yakitori-Classic-food-Japan.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_two_previmage = BusinessImage(business_id=21, user_id=2, image_url="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/9a/35/86/pretty-dragon-roll.jpg?w=600&h=400&s=1", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_three_previmage = BusinessImage(business_id=22, user_id=3, image_url="https://media-cdn.tripadvisor.com/media/photo-s/19/9f/67/be/ramen.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_four_previmage = BusinessImage(business_id=23, user_id=4, image_url="https://static.wixstatic.com/media/e2307d_0945e61a7e68427d8bf426e0826c32e2~mv2.jpg/v1/crop/x_512,y_0,w_5272,h_4200/fill/w_560,h_446,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/PartyTray-C_JPG.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_five_previmage = BusinessImage(business_id=24, user_id=5, image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxVwd4iB_S0gP0Q8F_Hjj8MMYGNpEkKW5nKg&usqp=CAU", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_six_previmage = BusinessImage(business_id=25, user_id=6, image_url="https://ik.imagekit.io/awwybhhmo/satellite_images/japanese/beyondmenu/about_us/13.jpg?tr=w-3840", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_seven_previmage = BusinessImage(business_id=26, user_id=7, image_url="https://s3-media0.fl.yelpcdn.com/bphoto/eoDhZ7wp2MHr01OEnQshwA/348s.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_one_previmage = BusinessImage(business_id=27, user_id=1, image_url="https://www.tasteatlas.com/images/toplistarticles/08c818739e4b48ce96d319c16f4cc0ca.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_two_previmage = BusinessImage(business_id=28, user_id=2, image_url="https://www.eatthis.com/wp-content/uploads/sites/4/media/images/ext/798104191/uno-pizzeria-whole-hog-burger.jpg?quality=82&strip=1", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_three_previmage = BusinessImage(business_id=29, user_id=3, image_url="https://eatkc.com/wp-content/uploads/2019/01/American-Food.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_four_previmage = BusinessImage(business_id=30, user_id=4, image_url="https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,f_jpg,g_xy_center,h_511,q_65,w_639,x_844,y_676/v1/clients/rochester/87060651_1567282676756020_7700319068246507520_n_31d52706-82bc-4aaf-853a-a40f7f057038.jpg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_five_previmage = BusinessImage(business_id=30, user_id=5, image_url="https://food.fnr.sndimg.com/content/dam/images/food/secured/fullset/2015/11/13/0/TE0203_5-Meatloaf-24-Diner_s4x3.jpg.rend.hgtvcom.616.462.suffix/1447686913255.jpeg", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_six_previmage = BusinessImage(business_id=30, user_id=6, image_url="https://images.getbento.com/accounts/3e3c9a975ad1b4ca467f67bf4419516e/media/images/3015213068AMERICAN_BRASS_June21_654.jpg?w=1200&fit=max&auto=compress,format", image_preview=True, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_one_image = BusinessImage(business_id=1, user_id=2, image_url="https://images.unsplash.com/photo-1556761223-4c4282c73f77?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3330&q=80", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_two_image = BusinessImage(business_id=2, user_id=3, image_url="https://i.insider.com/6164d16c2457a4001982d60b?width=700", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_three_image = BusinessImage(business_id=3, user_id=4, image_url="https://assets.site-static.com/userFiles/805/image/italian-food-restaurants-in-alexandria.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_four_image = BusinessImage(business_id=4, user_id=5, image_url="https://leonardobansko.com/wp-content/uploads/2017/07/italian-cuisine-one.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_five_image = BusinessImage(business_id=5, user_id=6, image_url="https://www.fluentu.com/blog/italian/wp-content/uploads/sites/23/2017/06/italian-restaurant-phrases-e1685781455884.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    italian_six_image = BusinessImage(business_id=6, user_id=1, image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIdG1OrhhHS7eZhK5rdoRw3TUrbGhD6G5TsA&usqp=CAU", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_one_image = BusinessImage(business_id=7, user_id=2, image_url="https://dailytaco.com/wp-content/uploads/2021/11/Home-Tacos.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_two_image = BusinessImage(business_id=8, user_id=3, image_url="https://i.insider.com/5e3ad7c1ab49fd79fc21a136?width=700", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_three_image = BusinessImage(business_id=9, user_id=4, image_url="https://images.getbento.com/accounts/ed339998bb0f57e6806b4673833e2211/media/images/20012shutterstock_412152928.jpg?w=1200&fit=max&auto=compress,format", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_four_image = BusinessImage(business_id=10, user_id=5, image_url="https://elpatronma.com/wp-content/uploads/2021/04/00100lPORTRAIT_00100_BURST20190803163927943_COVER_original.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_five_image = BusinessImage(business_id=11, user_id=6, image_url="https://www.englishclub.com/images/vocabulary/food/mexican/mexican-food.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_six_image = BusinessImage(business_id=12, user_id=7, image_url="https://images.squarespace-cdn.com/content/v1/58f78fed1b631bdf7c8687d6/1561483325531-WBV8H6Y75HGSBHY213D5/steak-and-shrimp-fajita.jpg?format=1500w", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    mexican_seven_image = BusinessImage(business_id=13, user_id=1, image_url="https://images.shawneemissionpost.com/wp-content/uploads/2023/07/Abelardos-1.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_one_image = BusinessImage(business_id=14, user_id=2, image_url="https://st2.depositphotos.com/1027198/46624/i/450/depositphotos_466241258-stock-photo-lebanese-food-selection-top-view.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_two_image = BusinessImage(business_id=15, user_id=3, image_url="https://s3-media0.fl.yelpcdn.com/bphoto/0kYoqz56M1rokJ5TKiiVAg/1000s.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_three_image = BusinessImage(business_id=16, user_id=4, image_url="https://media-cdn.tripadvisor.com/media/photo-s/0a/63/bb/41/large-mixed-grill-14.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_four_image = BusinessImage(business_id=17, user_id=5, image_url="https://cdn10.phillymag.com/wp-content/uploads/sites/3/2019/04/middle-eastern-restaurants-zahav-838x1024.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_five_image = BusinessImage(business_id=18, user_id=6, image_url="https://www.olivetreemenu.com/wp-content/uploads/2023/05//Middle-Eastern-Cuisine-Kent-WA-98030.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    middleast_six_image = BusinessImage(business_id=19, user_id=1, image_url="https://www.foodandwine.com/thmb/sYwPs2LIwtCIWt9q16x_1b_K37M=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Shishbarak-Incredible-Dumpling-Popping-Up-at-Restos-Across-the-Country-FT-BLOG0323-b3bf39e7b0c24dcf9a748b30011f16bc.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_one_image = BusinessImage(business_id=20, user_id=2, image_url="https://thumbs.dreamstime.com/b/takoyaki-octopus-balls-japanese-food-22624501.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_two_image = BusinessImage(business_id=21, user_id=3, image_url="https://rimage.gnst.jp/livejapan.com/public/article/detail/a/00/04/a0004391/img/basic/a0004391_main.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_three_image = BusinessImage(business_id=22, user_id=4, image_url="https://image-tc.galaxy.tf/wijpeg-75t2zsr2m8hy7cv30xyungk2s/chry-dining-kohaku-japanese-restaurant_standard.jpg?crop=0%2C0%2C667%2C500", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_four_image = BusinessImage(business_id=23, user_id=5, image_url="https://images.squarespace-cdn.com/content/v1/5e6ef5a95bceee1383e06242/1647145065968-LK2MZ16V6O6PNR6P4030/IMG_0762.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_five_image = BusinessImage(business_id=24, user_id=6, image_url="https://ik.imagekit.io/awwybhhmo/satellite_images/japanese/beyondmenu/hero/15.jpg?tr=w-3840,q-50", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_six_image = BusinessImage(business_id=25, user_id=7, image_url="https://ik.imagekit.io/awwybhhmo/satellite_images/japanese/red/about_us/10.jpg?tr=w-3840", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    jap_seven_image = BusinessImage(business_id=26, user_id=1, image_url="https://media-cdn.tripadvisor.com/media/photo-s/1c/8e/9d/e2/sapporo-japanese-restaurant.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_one_image = BusinessImage(business_id=27, user_id=2, image_url="https://www.corriecooks.com/wp-content/uploads/2023/05/american-food-2.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_two_image = BusinessImage(business_id=28, user_id=3, image_url="https://loveincorporated.blob.core.windows.net/contentimages/gallery/4893caea-06eb-465f-869a-1228df12b241-2-classic-steakhouse-steak.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_three_image = BusinessImage(business_id=29, user_id=4, image_url="https://dmn-dallas-news-prod.cdn.arcpublishing.com/resizer/GCe0IBHzlxk25v8PGoOj7HvlmJo=/1660x0/smart/filters:no_upscale()/cloudfront-us-east-1.images.arcpublishing.com/dmn/ZP4MPNGLEFAU3BT4FC53CMYLKI.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_four_image = BusinessImage(business_id=30, user_id=5, image_url="https://patch.com/img/cdn20/users/22896833/20230801/112028/styles/patch_image/public/pizzabeer___01111952100.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_five_image = BusinessImage(business_id=30, user_id=6, image_url="https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/gaihxodb/8f689aa6-9df4-4170-add2-29c1488d331e.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())
    american_six_image = BusinessImage(business_id=30, user_id=1, image_url="https://flatironsteakhouse.com/wp-content/uploads/2015/01/flatiron-slider-02-1.jpg", image_preview=False, created_at=datetime.datetime.now(), updated_at=datetime.datetime.now())

    db.session.add_all([
        italian_one_previmage, italian_two_previmage, italian_three_previmage, italian_four_previmage, italian_five_previmage, italian_six_previmage,
        mexican_one_previmage, mexican_two_previmage, mexican_three_previmage, mexican_four_previmage, mexican_five_previmage, mexican_six_previmage, mexican_seven_previmage,
        middleast_one_previmage, middleast_two_previmage, middleast_three_previmage, middleast_four_previmage, middleast_five_previmage, middleast_six_previmage,
        jap_one_previmage, jap_two_previmage, jap_three_previmage, jap_four_previmage, jap_five_previmage, jap_six_previmage, jap_seven_previmage,
        american_one_previmage, american_two_previmage, american_three_previmage, american_four_previmage, american_five_previmage, american_six_previmage,
        italian_one_image, italian_two_image, italian_three_image, italian_four_image, italian_five_image, italian_six_image,
        mexican_one_image, mexican_two_image, mexican_three_image, mexican_four_image, mexican_five_image, mexican_six_image, mexican_seven_image,
        middleast_one_image, middleast_two_image, middleast_three_image, middleast_four_image, middleast_five_image, middleast_six_image,
        jap_one_image, jap_two_image, jap_three_image, jap_four_image, jap_five_image, jap_six_image, jap_seven_image, american_one_image, american_two_image, american_three_image, american_four_image, american_five_image, american_six_image,
        ])

    db.session.commit()

def undo_businesses_images():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.business_images RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM business_images"))

    db.session.commit()
